import * as api from './api.js';
import * as state from './state.js';
import * as parser from './parser.js';
import * as task from './task.js';
import * as modes from './modes.js';
import * as compare from './compare.js';
import * as exportModule from './export.js';
import * as video from './video.js';
import * as tabs from './tabs.js';
import * as panels from './panels.js';

document.addEventListener('DOMContentLoaded', () => {
    const el_auto_id_1 = document.getElementById('auto_id_1');
    if (el_auto_id_1) el_auto_id_1.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.clearAllTasks() });
    const el_auto_id_2 = document.getElementById('auto_id_2');
    if (el_auto_id_2) el_auto_id_2.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  exportModule.sortTasksByNid() });
    const el_auto_id_3 = document.getElementById('auto_id_3');
    if (el_auto_id_3) el_auto_id_3.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  exportModule.exportResults() });
    const el_auto_id_4 = document.getElementById('auto_id_4');
    if (el_auto_id_4) el_auto_id_4.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  parser.importTasks() });
    const el_workspace_select = document.getElementById('workspace-select');
    if (el_workspace_select) el_workspace_select.addEventListener('change', function(event) { state.switchWorkspace(this.value) });
    const el_auto_id_5 = document.getElementById('auto_id_5');
    if (el_auto_id_5) el_auto_id_5.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  state.createWorkspace() });
    const el_auto_id_6 = document.getElementById('auto_id_6');
    if (el_auto_id_6) el_auto_id_6.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  state.showWorkspaceMenu() });
    const el_auto_id_7 = document.getElementById('auto_id_7');
    if (el_auto_id_7) el_auto_id_7.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  api.repairAllErrors() });
    const el_sidebar_expand_btn = document.getElementById('sidebar-expand-btn');
    if (el_sidebar_expand_btn) el_sidebar_expand_btn.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  compare.toggleSidebar() });
    const el_sidebar_collapse_btn = document.getElementById('sidebar-collapse-btn');
    if (el_sidebar_collapse_btn) el_sidebar_collapse_btn.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  compare.toggleSidebar() });
    const el_mode_segment = document.getElementById('mode-segment');
    if (el_mode_segment) el_mode_segment.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  modes.switchReviewMode('segment') });
    const el_mode_profile = document.getElementById('mode-profile');
    if (el_mode_profile) el_mode_profile.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  modes.switchReviewMode('profile') });
    const el_mode_audiovisual = document.getElementById('mode-audiovisual');
    if (el_mode_audiovisual) el_mode_audiovisual.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  modes.switchReviewMode('audiovisual') });
    const el_auto_id_8 = document.getElementById('auto_id_8');
    if (el_auto_id_8) el_auto_id_8.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  panels.showHelp() });
    const el_auto_id_9 = document.getElementById('auto_id_9');
    if (el_auto_id_9) el_auto_id_9.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  api.showSettings() });
    const el_auto_id_10 = document.getElementById('auto_id_10');
    if (el_auto_id_10) el_auto_id_10.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  parser.importTasks() });
    const el_timeline = document.getElementById('timeline');
    if (el_timeline) el_timeline.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  video.seekToPosition(event) });
    const el_auto_id_11 = document.getElementById('auto_id_11');
    if (el_auto_id_11) el_auto_id_11.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  video.seekRelative(-5) });
    const el_auto_id_12 = document.getElementById('auto_id_12');
    if (el_auto_id_12) el_auto_id_12.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  video.togglePlay() });
    const el_auto_id_13 = document.getElementById('auto_id_13');
    if (el_auto_id_13) el_auto_id_13.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  video.seekRelative(5) });
    const el_playback_rate = document.getElementById('playback-rate');
    if (el_playback_rate) el_playback_rate.addEventListener('change', function(event) { video.changePlaybackRate() });
    const el_comparison_mode_btn = document.getElementById('comparison-mode-btn');
    if (el_comparison_mode_btn) el_comparison_mode_btn.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  compare.toggleComparisonMode() });
    const el_current_task_label = document.getElementById('current-task-label');
    if (el_current_task_label) el_current_task_label.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  this.querySelector('div').classList.toggle('line-clamp-2') });
    const el_auto_id_14 = document.getElementById('auto_id_14');
    if (el_auto_id_14) el_auto_id_14.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  tabs.switchTab('text') });
    const el_auto_id_15 = document.getElementById('auto_id_15');
    if (el_auto_id_15) el_auto_id_15.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  tabs.switchTab('visual') });
    const el_auto_id_16 = document.getElementById('auto_id_16');
    if (el_auto_id_16) el_auto_id_16.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  tabs.switchTab('keyframe') });
    const el_time_jump_input = document.getElementById('time-jump-input');
    if (el_time_jump_input) el_time_jump_input.addEventListener('keydown', function(event) { if(event.key==='Enter'){video.jumpToInputTime(); event.preventDefault();} });
    const el_auto_id_17 = document.getElementById('auto_id_17');
    if (el_auto_id_17) el_auto_id_17.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  video.jumpToInputTime() });
    const el_auto_id_18 = document.getElementById('auto_id_18');
    if (el_auto_id_18) el_auto_id_18.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.skipTask() });
    const el_auto_id_19 = document.getElementById('auto_id_19');
    if (el_auto_id_19) el_auto_id_19.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.submitReview() });
    const el_auto_id_20 = document.getElementById('auto_id_20');
    if (el_auto_id_20) el_auto_id_20.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.skipTask() });
    const el_auto_id_21 = document.getElementById('auto_id_21');
    if (el_auto_id_21) el_auto_id_21.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.submitReview() });
    const el_rating_dock_toggle = document.getElementById('rating-dock-toggle');
    if (el_rating_dock_toggle) el_rating_dock_toggle.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  compare.toggleRatingDock() });
    const el_auto_id_22 = document.getElementById('auto_id_22');
    if (el_auto_id_22) el_auto_id_22.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.skipTask() });
    const el_auto_id_23 = document.getElementById('auto_id_23');
    if (el_auto_id_23) el_auto_id_23.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.submitReview() });
    const el_auto_id_24 = document.getElementById('auto_id_24');
    if (el_auto_id_24) el_auto_id_24.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.skipTask() });
    const el_auto_id_25 = document.getElementById('auto_id_25');
    if (el_auto_id_25) el_auto_id_25.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.submitReview() });
    const el_auto_id_26 = document.getElementById('auto_id_26');
    if (el_auto_id_26) el_auto_id_26.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.submitReview() });
    const el_auto_id_27 = document.getElementById('auto_id_27');
    if (el_auto_id_27) el_auto_id_27.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  task.skipTask() });
    const el_auto_id_28 = document.getElementById('auto_id_28');
    if (el_auto_id_28) el_auto_id_28.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  parser.closeImportModal() });
    const el_import_file = document.getElementById('import-file');
    if (el_import_file) el_import_file.addEventListener('change', function(event) { parser.onImportFileChange(this) });
    const el_auto_id_29 = document.getElementById('auto_id_29');
    if (el_auto_id_29) el_auto_id_29.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  document.getElementById('import-file').click() });
    const el_auto_id_30 = document.getElementById('auto_id_30');
    if (el_auto_id_30) el_auto_id_30.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  panels.showFormatHelp() });
    const el_auto_id_31 = document.getElementById('auto_id_31');
    if (el_auto_id_31) el_auto_id_31.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  parser.closeImportModal() });
    const el_auto_id_32 = document.getElementById('auto_id_32');
    if (el_auto_id_32) el_auto_id_32.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  parser.confirmImport() });
    const el_auto_id_33 = document.getElementById('auto_id_33');
    if (el_auto_id_33) el_auto_id_33.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  panels.closeHelpModal() });
    const el_auto_id_34 = document.getElementById('auto_id_34');
    if (el_auto_id_34) el_auto_id_34.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  api.closeSettingsModal() });
    const el_llm_use_default = document.getElementById('llm-use-default');
    if (el_llm_use_default) el_llm_use_default.addEventListener('change', function(event) { api.toggleDefaultLLM(this.checked) });
    const el_auto_id_35 = document.getElementById('auto_id_35');
    if (el_auto_id_35) el_auto_id_35.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  api.closeSettingsModal() });
    const el_auto_id_36 = document.getElementById('auto_id_36');
    if (el_auto_id_36) el_auto_id_36.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  api.saveLLMSettings() });
    const el_repair_confirm_btn = document.getElementById('repair-confirm-btn');
    if (el_repair_confirm_btn) el_repair_confirm_btn.addEventListener('click', function(event) { event.preventDefault(); event.stopPropagation();  api.closeRepairModal() });
});
